
package ru.javarush.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://ws.javarush.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloString", targetNamespace = "http://ws.javarush.ru/", className = "ru.javarush.ws.GetHelloString")
    @ResponseWrapper(localName = "getHelloStringResponse", targetNamespace = "http://ws.javarush.ru/", className = "ru.javarush.ws.GetHelloStringResponse")
    @Action(input = "http://ws.javarush.ru/HelloWebService/getHelloStringRequest", output = "http://ws.javarush.ru/HelloWebService/getHelloStringResponse")
    public String getHelloString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
